IBM/continuous-delivery-go-sdk

cdtoolchainv2/cd_toolchain_v2.go
cdtoolchainv2/cd_toolchain_v2_test.go

New sdk after swagger change

---

cdtoolchainv2/cd_toolchain_v2.go
cdtoolchainv2/cd_toolchain_v2_test.go

Remove eu-fr2 and mon01 api endpoints

---

README.md

Updates to text and hyperlinks in README.md concerning the Beta nature of the SDK and related API Docs.
N/A - README.md updates only.
N/A - README.md updates only.

Update disclaimer, hyperlinks

---

README.md

Update README to link to API docs.
N/A - README change only
N/A - README change only

Add links to API docs

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_examples_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_integration_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

Updated SDK for tekton pipelines v2. 
Adjusted the required/computed state of some properties. Used a newer version of the sdk generator also, which has added some extra functions.

Update tekton go sdk

---

cdtoolchainv2/cd_toolchain_v2.go
cdtoolchainv2/cd_toolchain_v2_test.go

Latest toolchain SDK produced from otc-api swagger

---

.bumpversion.cfg
.travis.yml
CHANGELOG.md
README.md
common/version.go

chore:(tekton): update readme and version references

---

RELEASE_NOTES.md

Update schedule in RELEASE_NOTES since Terraform Provider v1.46.0 was published Oct. 3
N/A - doc change only
N/A - doc change only

Update schedule in RELEASE_NOTES

---

cdtoolchainv2/cd_toolchain_v2.go
cdtoolchainv2/cd_toolchain_v2_test.go

Signed-off-by: Gary Marjoram <marjoram@ie.ibm.com>

fix(toolchain): Added UI href property in toolchain response

---

CONTRIBUTING.md

Documentation update. Mainly to cause an auto-build of the SDK

fix(tekton): documentation change

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_examples_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_integration_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

Large set of changes based on the internal v2 API review: https://github.ibm.com/CloudEngineering/api-standards/issues/127
Summary
- Many strings updates and doc improvements
- Restructured `resource_group_id` into `resource_group: { id: "..." }`
- Reshaped `service_instance_id` into `tool: { id: "..." }`
- Updated all integration tests to fix broken tests, match current API functionality and get a green suite
Breaking Changes:
- `disabled` property in triggers renamed to `enabled`
- `enable_slack_notifications` renamed to `enable_notifications` in pipeline
- `events` reshaped from object of booleans to array of strings, e.g. `events: ["push", "pull_request"]`
- Reshaped `scm_source` to `source` and reshaped internal properties …

fix(tekton): Tekton v2 API GA review

---

RELEASE_NOTES.md

Add pending release notes

---

RELEASE_NOTES.md

Add some missing rlease notes for the new release

chore(tekton): Add missing release notes

---

RELEASE_NOTES.md

chore(tekton): fix release note typo

---

RELEASE_NOTES.md

Add documentation for new `type` values in git tool integrations to the release notes.

docs: new type values for git integrations

---

cdtoolchainv2/cd_toolchain_v2.go
cdtoolchainv2/cd_toolchain_v2_test.go

Signed-off-by: Omar Al Bastami <omar.albastami@ibm.com>
Removed `tags` property from toolchain SDK

remove 'tags' from toolchain SDK

---

RELEASE_NOTES.md

Update RELEASE_NOTES.md for latest changes to the APIs/SDK.
N/A - Update to release notes
N/A - Update to release notes

Add latest release notes

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_examples_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

Final review of API has resulted in the following changes
- Remove `offset` option from API docs, when fetching pipeline runs
- Remove default values for booleans in PATCH requests
- Clean up related Strings for the above

fix(tekton): final GA review changes

---

RELEASE_NOTES.md

Goal of this PR is to create a new `v1.0.0` tag/release in github and we will subsequently create a `v1.0.1` release. This is to allow us to retract the original `v1.0.0` that was published erroneously to https://pkg.go.dev/github.com/IBM/continuous-delivery-go-sdk?tab=versions

feat(build): trigger major version build

---

RELEASE_NOTES.md

N/A: Release notes update only
N/A: Release notes update only

Update release notes: 0.1.9

---

README.md
RELEASE_NOTES.md

N/A: Doc updates only
N/A: Doc updates only

fix(doc): Promote Open Beta to GA

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_examples_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_integration_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_suite_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

After GA of the Tekton V2 APIs, some changes were added that were not included in the GA release. Updating the Go SDK to match the latest API.
The backend changes have been merged

Tekton updates after the V2 API GA

---

.gitignore
.travis.yml
package.json

Issue: https://github.ibm.com/org-ids/roadmap/issues/24099
Fix the sem ver build issue that recently arose, following guidance from the SDK template team
Following this example: https://github.com/IBM/platform-services-go-sdk/commit/2736115b39d7ca9a61e7301ccc3356c1ba29a7fb
Details are explained in Phil Adam's [#ibm-sdk-generation Jsn. 10 post](https://ibm-cloudplatform.slack.com/archives/C4XC6SWKG/p1673368244638439)

fix(build): fix sem-ver build issue

---

package.json

Remove release config from package.json to see if it fixes the travis build pipeline
After merging a PR, no travis build is triggered
Hopefully travis build will auto trigger after this PR is merged

fix(build): remove release line from package.json

---

package.json

Signed-off-by: Omar Al Bastami <omar.albastami@ibm.com>
Modified package.json to revert to version 0.0.0 since this is not a real package, and is simply being used to feed semantic release dependencies.

build: fix semantic release package.json

---

README.md

chore(doc): add Go pkg link to README

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go
go.mod

Add support for `next_build_number` property in Tekton Pipelines

feat(tekton): add next build number support

---

.travis.yml
go.mod
go.sum

build: add latest changes from template

---

go.mod
go.sum

build: bump core dependency

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_examples_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

One string update and some name changes in test files. No functional change

chore(tekton): update examples

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

Add trigger.favorite support. Also some minor documentation updates

fix(tekton): add trigger favorite field

---

.travis.yml
Makefile
README.md
go.mod
go.sum

Fixes the GPG errors in travis builds, bumped go core version as well, modified Makefile as well.

build: avoid GPG errors and bump Go versions

---

cdtoolchainv2/cd_toolchain_v2.go
cdtoolchainv2/cd_toolchain_v2_examples_test.go
cdtoolchainv2/cd_toolchain_v2_integration_test.go
cdtoolchainv2/cd_toolchain_v2_suite_test.go
cdtoolchainv2/cd_toolchain_v2_test.go

Supporting `name` parameter when retrieving toolchain collection

feat(toolchain): add name query param to list toolchains

---

.travis.yml

fix: upgrade deploy go version in travis build

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

feat(tekton): add eu-es region

---

.secrets.baseline
cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go
cdtoolchainv2/cd_toolchain_v2.go
cdtoolchainv2/cd_toolchain_v2_examples_test.go
cdtoolchainv2/cd_toolchain_v2_integration_test.go
cdtoolchainv2/cd_toolchain_v2_test.go

feat: support eu-es region

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

Add support for locking properties in Tekton pipelines. When enabled, this prevents a property from being over-ridden at trigger level or when running the Pipeline.

feat(tekton): Add property locking support

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

Add support for CEL filtering of Git triggers in tekton pipeline

feat(tekton): add support for CEL filtering

---

cdtoolchainv2/cd_toolchain_v2_integration_test.go

Refactor integration tests for toolchain

test(toolchain): refactor integration tests

---

.secrets.baseline

doc: update secrets baseline

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go

Add option to enable/disable fork events in git triggers

feat(tekton): Add fork events option

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

Add full support for the "enable events from forks" feature to Tekton Git triggers

fix(tekton): full support for fork feature

---

cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_examples_test.go
cdtektonpipelinev2/cd_tekton_pipeline_v2_test.go

Generate Tekton Go SDK code using the latest version of the SDK generator. Adds improved error handling

fix(tekton): regenerate tekton after openapi lint fixes

---

README.md
cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtoolchainv2/cd_toolchain_v2.go
cdtoolchainv2/cd_toolchain_v2_integration_test.go

Added the `/v2` path in the common module.

fix: add v2 path in common module

---

.bumpversion.toml
CHANGELOG.md
README.md
cdtektonpipelinev2/cd_tekton_pipeline_v2.go
cdtoolchainv2/cd_toolchain_v2.go
common/version.go

chore: revert commits to version 2.0.1

---

.travis.yml

Further debugging the problem with the Go semantic-release build

Build maintenance

---

.travis.yml

chore: debug Go build issue
